# Generated by Django 2.2.6 on 2019-10-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_one', models.TextField(max_length=170, verbose_name='Descripción uno')),
                ('description_two', models.TextField(max_length=280, verbose_name='Descripción dos')),
                ('imagen_profile', models.ImageField(upload_to='', verbose_name='Imagen de perfil')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
