# Generated by Django 2.2.6 on 2019-10-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description_one',
            field=models.CharField(max_length=170, verbose_name='Descripción uno'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_two',
            field=models.CharField(max_length=280, verbose_name='Descripción dos'),
        ),
    ]
